apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 02 - statefulset mysql.yaml
- 03 - deployment backend.yaml

secretGenerator:
- name: pass-mysql
  literals:
  - clave=V0c@L3S

configMapGenerator:
- name: java-config
  files:
  - propiedades.properties
